<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Case Study: Comparing Two Groups</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b1e7e8ee10296b6f6820b1334157194.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="”https://siteimproveanalytics.com/js/siteanalyze_6294756.js”"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles.css">
<link rel="stylesheet" href="../style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Modules/00-OverviewIntro.html">Modules</a></li><li class="breadcrumb-item"><a href="../Modules/08-CaseStudy2Groups.html">Case Study: Comparing Two Groups</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/stat_bear.png" alt="UC Berkeley Statistics logo" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../assets/stat_bear.png" alt="UC Berkeley Statistics logo" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Stat 135</a> 
        <div class="sidebar-tools-main">
    <a href="{{< var site-url >}}" title="" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home / Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../staff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Staff</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../calendar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendar</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Modules</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/00-OverviewIntro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/01-ThinkProb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Thinking probabilistically about data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/02-EstimationBasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/03-CaseStudyRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Case Study: Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/04-CreatingEstimators.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating Estimators with MLE</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/05-LossMEstimators.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimating with Loss Functions and M-Estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/06-SamplingDist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling distribution of the Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/07-CIMean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence Intervals for the Population Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modules/08-CaseStudy2Groups.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Case Study: Comparing Two Groups</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../license.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#modeling-two-groups" id="toc-modeling-two-groups" class="nav-link active" data-scroll-target="#modeling-two-groups">Modeling two groups</a>
  <ul class="collapse">
  <li><a href="#relationship-of-these-models-to-regression" id="toc-relationship-of-these-models-to-regression" class="nav-link" data-scroll-target="#relationship-of-these-models-to-regression">Relationship of these models to Regression</a></li>
  </ul></li>
  <li><a href="#independent-groups" id="toc-independent-groups" class="nav-link" data-scroll-target="#independent-groups">Independent Groups</a>
  <ul class="collapse">
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  <li><a href="#ci-for-two-sample-comparisons" id="toc-ci-for-two-sample-comparisons" class="nav-link" data-scroll-target="#ci-for-two-sample-comparisons">CI for Two-Sample Comparisons</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#assuming-equal-variance" id="toc-assuming-equal-variance" class="nav-link" data-scroll-target="#assuming-equal-variance">Assuming Equal Variance</a></li>
  <li><a href="#example-redo" id="toc-example-redo" class="nav-link" data-scroll-target="#example-redo">Example Redo</a></li>
  </ul></li>
  <li><a href="#paired-data" id="toc-paired-data" class="nav-link" data-scroll-target="#paired-data">Paired Data</a>
  <ul class="collapse">
  <li><a href="#estimation-1" id="toc-estimation-1" class="nav-link" data-scroll-target="#estimation-1">Estimation</a></li>
  <li><a href="#ci" id="toc-ci" class="nav-link" data-scroll-target="#ci">CI</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Modules/00-OverviewIntro.html">Modules</a></li><li class="breadcrumb-item"><a href="../Modules/08-CaseStudy2Groups.html">Case Study: Comparing Two Groups</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Case Study: Comparing Two Groups</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="READING">
<div class="block-title">
<p><strong>Corresponding reading</strong></p>
</div>
<ul>
<li>Chapter 4.5 of <span class="citation" data-cites="agresti2021">Agresti and Kateri (<a href="#ref-agresti2021" role="doc-biblioref">2021</a>)</span>.</li>
<li>Chapter 11 of <span class="citation" data-cites="rice2006">Rice (<a href="#ref-rice2006" role="doc-biblioref">2006</a>)</span> (11.3 in particular for paired samples, not covered in <span class="citation" data-cites="agresti2021">Agresti and Kateri (<a href="#ref-agresti2021" role="doc-biblioref">2021</a>)</span>)</li>
</ul>
</div>
<p>So far we have only considered creating confidence intervals for the mean of a single population. Now we are going to consider what if we have two different populations.</p>
<p>Consider the following examples:</p>
<ol type="1">
<li>We are interested in the difference in wages between men and women. We collect a random sample of men and women to and ask them their annual income.</li>
<li>We are interested the effect of rewards on behavior. We randomly select laboratory mice, with a treatment group getting rewards for successfully accomplishing a task and the control group receiving nothing.</li>
<li>We are interested in the effect of a weight loss drug. We collect the weight of subjects before and after they use the drug.</li>
<li>We want to compare political opinions between generations. We randomly recruit families and recruit two members to answer a survey, one of age 18-30 and the other of age 45-60.</li>
</ol>
<p>These examples all have the common property that we are trying to compare two populations, rather than estimate something about <em>one</em> population.</p>
<div class="GOALS">
<div class="block-title">
<p><strong>Questions/Goals for this Module</strong></p>
</div>
<ul>
<li>How to model comparisons between two groups</li>
<li>Extend CI concepts to two groups.</li>
<li>Understand the statistical differences between paired and unpaired data</li>
</ul>
</div>
<section id="modeling-two-groups" class="level2">
<h2 class="anchored" data-anchor-id="modeling-two-groups">Modeling two groups</h2>
<p>We can consider that we have data from two populations <span class="math display">\[(X_1,\ldots,X_{n_X}) \text{ and } (Y_1,\ldots, Y_{n_Y})\]</span> Since these are two different populations, we consider that they each have a different mean, but we’ll assume that within each group their means are the same, <span class="math display">\[E(X_i)=\mu_X, E(Y_i)=\mu_Y\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>I am deviating from the book’s notation here. The book has group 1 be <span class="math inline">\(Y_{11},\ldots,Y_{1n_1}\)</span> and the second group <span class="math inline">\(Y_{21},\ldots,Y_{2n_2}\)</span>, with means <span class="math inline">\(\bar{Y}_1\)</span> and <span class="math inline">\(\bar{Y}_2\)</span>. The book’s notation fits into our regression notation better, but I find from past experience that students find double indices harder to follow – and they are harder to write on the board!</p>
</div>
</div>
<p>What are common <em>additional</em> modeling choices that we might make?</p>
<ol type="1">
<li><p><strong>What do we estimate?</strong> The important question with all these parameters floating around is what are we interested in estimating? We could be interested in <span class="math inline">\(\mu_X\)</span> and <span class="math inline">\(\mu_Y\)</span> separately. But in many two group comparisons, we are primarily interested in comparing the two groups. This usually translates into evaluating how different these means are from each other. So we might define another parameter <span class="math display">\[\Delta=\mu_X-\mu_Y.\]</span> This is an example of creating a parameter of interest that isn’t explicitly a parameter of our distribution, but rather a function of our parameters.</p></li>
<li><p><strong>Dependence Structure</strong>: We could assume that within each group the <span class="math inline">\(X_i\)</span> are independent from each other and the <span class="math inline">\(Y_i\)</span> are independent from each other. This would make sense if each observation in the group comes from a different individual. What about between the <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span>? This depends on the data we are considering.</p>
<p>In our first two examples, each <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_j\)</span> are from separate individuals/units. It seems reasonable to assume that each response <span class="math inline">\(X_i\)</span> is independent from each <span class="math inline">\(Y_j\)</span>. However, in the last two, the <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> are measurements that are linked in some way: in example 3 measurement <span class="math inline">\(X_j\)</span> is the before and <span class="math inline">\(Y_j\)</span> the after on the same individual; in example 4, <span class="math inline">\(X_j\)</span> is the answer of the younger person and <span class="math inline">\(Y_j\)</span> is the answer of the older person <em>in the same family</em>. It does <em>not</em> make sense to assume they are independent. Knowing the weight of an individual before treatment gives you information about what their weight might be after treatment (you have different expectations of the final weight for someone who starts out 180lbs versus 240lbs).</p>
<p>This is called <strong>paired data</strong>, because the data comes in the form of pairs (and thus <span class="math inline">\(n_X=n_Y\)</span>). In fact we could instead think of the data as pairs indexed by the same value: <span class="math inline">\((X_1,Y_1),\ldots,(X_n,Y_n)\)</span>. In which case it might make sense to think of the <em>pairs</em> <span class="math inline">\((X_i,Y_i)\)</span> as independent from each other – i.e.&nbsp;to rewrite our data as observations <span class="math inline">\(i\)</span> which consist of a vector <span class="math inline">\((X_i,Y_i)\)</span>. However, note that the <span class="math inline">\(ith\)</span> pair wouldn’t necessarily correspond to the same unit. For example, in our example 4, <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> are from two <em>different people</em> but they are from the same household <span class="math inline">\(i\)</span>.</p></li>
<li><p> We could also consider what is an appropriate parametric model for our data. If our <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> data are both continuous, we are likely to choose a normal distribution, <span class="math display">\[X_i \overset{i.i.d}{\sim}N(\mu_X,\sigma^2_X),
Y_i \overset{i.i.d}{\sim}N(\mu_Y,\sigma^2_Y).\]</span></p>
<p>If our data are binary, then we would often use a Bernoulli model, <span class="math display">\[X_i \overset{i.i.d}{\sim}Be(\pi_X),
Y_i \overset{i.i.d}{\sim}Be(\pi_Y).\]</span></p>
<p>Notice that this doesn’t address correlation between the <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span>, which we might have to consider if we have paired data. We might, for example, assume that they are bivariate normal, with covariance, <span class="math display">\[cov(X_i,Y_i)=\sigma_{XY}\]</span> However, we will see for paired data, we can avoid needing to explicitly model (or estimate) <span class="math inline">\(\sigma_{XY}\)</span>.</p></li>
</ol>
<section id="relationship-of-these-models-to-regression" class="level3">
<h3 class="anchored" data-anchor-id="relationship-of-these-models-to-regression">Relationship of these models to Regression</h3>
<p>We have already discussed the example of two groups implicitly, when we looked at regression for the case of where our predictor <span class="math inline">\(X\)</span> was binary. We had, <span class="math display">\[E(Y |X)= \begin{cases}
\alpha_1, &amp; X=1\\
\alpha_0, &amp; X=0
\end{cases}
\]</span> So in this chapter, we’ve changed the notation (<span class="math inline">\(X\)</span> means something different in the regression frame work), but it is ultimately describing the same setting.</p>
<p>We also previously introduced a parametric for independent <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(X_i\)</span> categorical, <span class="math display">\[Y |X \sim \begin{cases}
N(\alpha_1,\sigma_1^2), &amp; X=1\\
N(\alpha_0,\sigma_0^2), &amp; X=0
\end{cases}
\]</span> This is the standard model for independent, non-paired data, and matches our model above. This model, however, didn’t handle dependency between our data, as we have with paired data.</p>
<p>Moreover, if instead we consider the standard regression model for linear models, <span class="math display">\[Y_i=\beta_0+\beta_1 X_i +\epsilon_i\]</span> with <span class="math inline">\(\epsilon_i\)</span> i.i.d. <span class="math inline">\(N(0,\sigma^2)\)</span>, then it doesn’t even allow for different variances in the two groups. So while the general notation and framework of regression works for two groups, the specific analysis we usually do with the standard model doesn’t match what is usually done for analyzing even two independent groups.</p>
<div class="QUESTION">
<div class="block-title">
<p><strong>Exercise/Question</strong></p>
</div>
<p>Convert our two-group modeling notation above into the regression notation. What is <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> in each of our examples in the regression notation rather than the 2-group notation?</p>
</div>
</section>
</section>
<section id="independent-groups" class="level2">
<h2 class="anchored" data-anchor-id="independent-groups">Independent Groups</h2>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<p>In this case, if the two populations are independent from each other, we’ve actually already calculated (in section) the MLE assuming normality of the parameters as a special case of the regression model, <span class="math display">\[
\begin{gathered}
\hat\mu_X=\bar{X},\quad
\hat\mu_Y=\bar{Y}\\
\hat\sigma_X^2=\frac{1}{n_X}\sum_{i=1}^{n_X} (X_i-\bar{X})^2,\quad
\hat\sigma_Y^2=\frac{1}{n_Y}\sum_{i=1}^{n_Y} (Y_i-\bar{Y})^2
\end{gathered}
\]</span> However, as is standard, we will instead use the estimates <span class="math display">\[S^2_X=\frac{1}{n_X-1}\sum_{i=1}^{n_X} (X_i-\bar{X})^2, \quad
S^2_Y=\frac{1}{n_Y-1}\sum_{i=1}^{n_Y} (Y_i-\bar{Y})^2\]</span></p>
<p>We also can state the distributions of <span class="math inline">\(\hat{\mu}_X\)</span> and <span class="math inline">\(\hat{\mu}_Y\)</span>, either exactly – if we assume normality – or approximately if we rely on the central limit theorem, <span class="math display">\[\hat{\mu}_X\sim N(\mu_X,\sigma^2_X/n_X), \quad \hat{\mu}_Y\sim N(\mu_Y,\sigma^2_Y/n_Y)\]</span></p>
<p>What about <span class="math inline">\(\Delta\)</span>? The obvious estimator for their difference is<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>: <span class="math display">\[\hat\Delta=\hat\mu_X-\hat\mu_Y\]</span></p>
<p>What is the distribution of <span class="math inline">\(\hat\Delta\)</span>? We’ve already seen that linear combinations of normal variables are normal. That is also true for asymptotic distributions:</p>
<div id="thm-asymLinearComb" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1</strong></span> If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> both converge asymptotically to a normal distribution, then <span class="math inline">\(aX+bY\)</span> will also converge to asymptotically to a normal distribution.</p>
</div>
<p>So depending on what assumptions we want to make, we have either</p>
<ol type="1">
<li>We assume <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are both i.i.d. normal, then <span class="math inline">\(\hat\Delta\)</span> is exactly normally distributed</li>
</ol>
<p>or</p>
<ol start="2" type="1">
<li>Our <span class="math inline">\(n_X\)</span> <em>and</em> <span class="math inline">\(n_Y\)</span> are sufficiently large so that <span class="math inline">\(\hat\Delta\)</span> is approximately normal by the CLT theorem.</li>
</ol>
<p>Therefore, since <span class="math inline">\(\hat\Delta\)</span> is normal (or approximately so), we just need to figure out what should be the mean and variance of that normal. Clearly the expectation is just, <span class="math display">\[E(\hat\Delta)=\mu_X-\mu_Y\]</span> The variance is given by <span class="math display">\[var(\hat\Delta)=var(\bar{X})+var(\bar{Y})-2cov(\hat\mu_X,\hat\mu_Y)\]</span> So for independent groups, <span class="math inline">\(cov(\hat\mu_X,\hat\mu_Y)=0\)</span> so we have that the variance of <span class="math inline">\(\hat{\Delta}\)</span> is, <span class="math display">\[\sigma^2_{\hat\Delta}=var(\hat\Delta)=\frac{\sigma_X^2}{n_X}+\frac{\sigma_Y^2}{n_Y}\]</span> We can estimate that variance by substituting in <span class="math inline">\(S^2_{X}\)</span> and <span class="math inline">\(S^2_{Y}\)</span> for <span class="math inline">\(\sigma^2_X\)</span> and <span class="math inline">\(\sigma^2_Y\)</span>, which gives us an estimate of the standard error, <span class="math display">\[S_{\hat\Delta}=\sqrt{\frac{S_X^2}{n_X}+\frac{S_Y^2}{n_Y}}\]</span></p>
</section>
<section id="ci-for-two-sample-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="ci-for-two-sample-comparisons">CI for Two-Sample Comparisons</h3>
<p>Just like our mean, we can consider the quantity <span class="math display">\[T_{\Delta}=\frac{\hat\Delta-\Delta}{S_{\hat{\Delta}}}=\frac{(\bar{X}-\bar{Y})-(\mu_X-\mu_Y)}{\sqrt{\frac{S_X^2}{n_X}+\frac{S_Y^2}{n_Y}}}\]</span> This is the same form as our previous T statistic: the difference of our estimator and the parameter, divided by the estimate of standard error of the estimator.</p>
<p>The same logic holds as in the one sample case:</p>
<ol type="1">
<li>If <span class="math inline">\(n\)</span> is large, then <span class="math inline">\(T_{\Delta}\)</span> converges to a <span class="math inline">\(N(0,1)\)</span> distribution, <span class="math display">\[T_{\Delta} \overset{D}{\rightarrow}  N(0,1).\]</span> and we have a CI <span class="math display">\[\hat{\Delta}\pm z_\alpha S_{\hat{\Delta}}\]</span></li>
<li>If <span class="math inline">\(n\)</span> is small, and we are willing to assume <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are normally distributed, then we will use a <span class="math inline">\(t\)</span>-distribution for <span class="math inline">\(T_{\Delta}\)</span> and get a CI <span class="math display">\[\hat{\Delta}\pm t_{\nu,\alpha} S_{\hat{\Delta}}\]</span> <span class="math inline">\(\nu\)</span> is a complicated function of <span class="math inline">\(n_X\)</span> and <span class="math inline">\(n_Y\)</span> as well as the <span class="math inline">\(S_X\)</span> and <span class="math inline">\(S_Y\)</span>, but can often be substituted with <span class="math inline">\(min(n_X-1,n_Y-1)\)</span> if one were to actually calculate the values by hand (rather than use a built-in function).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> This is a conservative choice, meaning it is the smallest possible value that <span class="math inline">\(\nu\)</span> could be, so it gives you the largest possible <span class="math inline">\(t_{\nu,\alpha}\)</span> (and thus the widest intervals)</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Technically <span class="math inline">\(T\)</span> does not follow the <span class="math inline">\(t\)</span> distribution exactly, even if the data are exactly normaly distributed. Rather, the use of of <span class="math inline">\(t_\nu\)</span> gives an approximation to the distribution of <span class="math inline">\(T\)</span>, called the <strong>Welch’s t-interval</strong>.</p>
</div>
</div>
</section>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>A drug company has developed a new drug to reduce hypertension. A sample of 15 patients are chosen to test the drug. Their systolic BP is reduced by 28.3 mmHg with a sample SD of 12 mmHg. The control group of 20 patients takes the standard drug and the average BP is reduced by 17.1 mmHg with the sample SD of 11.84 mmHg. Find a 95% CI for the difference in mean reduction of systolic BP, and conduct a two sided hypothesis test for the treatment making no difference.</p>
<p>The samples are small enough that to get a confidence interval, we are going to need to assume that <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span> are normal and rely on the <span class="math inline">\(t\)</span>-distribution.</p>
<p>We’ll let the treatment group be the <span class="math inline">\(Y\)</span>, so we have <span class="math inline">\(n_Y = 15\)</span>, and the control group be <span class="math inline">\(X\)</span>, <span class="math inline">\(n_X = 20\)</span>.</p>
<ul>
<li>Average systolic BP for the treatment group reduced by <span class="math inline">\(\bar{x} = 28.3\)</span> mmHg, <span class="math inline">\(S_x = 12\)</span> mmHg.</li>
<li>Average systolic BP for the control group reduced by <span class="math inline">\(\bar{y} = 17.1\)</span> mmHg, <span class="math inline">\(S_y = 11.84\)</span> mmHg.</li>
</ul>
<p><span class="math display">\[\hat{\Delta}=28.3-17.1=11.2\]</span> <span class="math display">\[S_{\hat\Delta} = \sqrt{\frac{S_X^2}{n_X}+\frac{S_Y^2}{n_Y}}=\sqrt{(12)^2/20+(11.84)^2/15}\approx 4.06\]</span> If we want to do our 95% confidence interval by hand, we get <span class="math inline">\(df=min(15-1,20-1)=14\)</span> which gives us</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.144787</code></pre>
</div>
</div>
<p>and our confidence interval as <span class="math display">\[\hat{\Delta}\pm t_{\nu,\alpha} S_{\hat{\Delta}}=11.2\pm 2.14 \cdot 4.06=11.2\pm 8.71\]</span> The more careful calculation of <span class="math inline">\(\nu\)</span>, our degrees of freedom gives</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.42119</code></pre>
</div>
</div>
<p>which gives</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.041091</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{\Delta}\pm t_{\nu,\alpha} S_{\hat{\Delta}}=11.2\pm 2.04 \cdot 4.06=11.2\pm 8.28\]</span> So, as expected, using our “by hand” version of <span class="math inline">\(min(n_X-1,n_Y-1)\)</span></p>
</section>
<section id="assuming-equal-variance" class="level3">
<h3 class="anchored" data-anchor-id="assuming-equal-variance">Assuming Equal Variance</h3>
<p>If we assume equal variance <span class="math inline">\(\sigma^2\)</span> in the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> groups, then you showed in homework that the MLE of <span class="math inline">\(\mu_X\)</span> and <span class="math inline">\(\mu_Y\)</span> doesn’t change, and the MLE of <span class="math inline">\(\sigma^2\)</span> is <span class="math display">\[\hat\sigma^2_{pooled}=\frac{n_X}{n_X+n_Y}\hat\sigma_X^2+\frac{n_Y}{n_X+n_Y}\hat\sigma_Y^2=\frac{1}{n_X+n_Y}\left(\sum_{i=1}^{n_X}(X_i-\bar{X})^2+\sum_{i=1}^{n_Y}(Y_i-\bar{Y})^2\right)\]</span> a weighted combination of the MLE in each group separately.</p>
<p>Unsurprisingly, there is an alternative form of the estimator based on <span class="math inline">\(S_X\)</span> and <span class="math inline">\(S_Y\)</span>, <span class="math display">\[
\begin{aligned}
S^2_{pooled}&amp;=\frac{n_X-1}{(n_X-1)+(n_Y-1)}S_X^2+\frac{n_Y-1}{(n_X-1)+(n_Y-1)}S_Y^2\\
&amp;=
\frac{1}{n_X+n_Y-2}\left(\sum_{i=1}^{n_X}(X_i-\bar{X})^2+\sum_{i=1}^{n_Y}(Y_i-\bar{Y})^2\right).\end{aligned}\]</span></p>
<p>This is called a <strong>pooled estimate of variance</strong>. It can be interpreted as estimating the variance in each group and then combining them for an estimate of their shared variance. But we can also see that it is basically combining the data together to get a single estimate of standard deviation across all the observations <em>pooled</em> together.</p>
<p>Using this estimate, gives us a <span class="math inline">\(T\)</span> statistic with a <span class="math inline">\(t\)</span> distribution.</p>
<p><span class="math display">\[
T_{\Delta,pooled} = \frac{\hat\Delta-\Delta}{\hat\sigma_{\hat\Delta,pooled}}=\frac{(\bar{X}-\bar{Y}) - (\mu_X - \mu_Y)}{S_{pooled}\sqrt{\tfrac{1}{n_X}+\tfrac{1}{n_Y}}} \sim t_{n_X+n_Y-2}
\]</span> It’s distribution is clear from our previous theorems in the one-sample case (and unlike the unequal variance case, is exact if we assume normality of our data).</p>
<div id="thm-two-sample-t" class="theorem">
<p><span class="theorem-title"><strong>Theorem 2</strong></span> If we have two independent samples <span class="math inline">\(X_1, \ldots, X_{n_X} \overset{i.i.d.}{\sim} N(\mu_X, \sigma_X^2)\)</span>, <span class="math inline">\(Y_1, \ldots, Y_m \overset{i.i.d.}{\sim} N(\mu_Y, \sigma_Y^2)\)</span>, and <span class="math inline">\(\sigma_X^2 = \sigma_Y^2\)</span>, , then <span class="math display">\[
T_{\Delta,pooled}  = \frac{(\bar{X}-\bar{Y}) - (\mu_X - \mu_Y)}{S_{pooled}\sqrt{\tfrac{1}{n_X}+\tfrac{1}{n_Y}}} \sim t_{n_X+n_Y-2}
\]</span></p>
</div>
<p>This gives the confidence interval</p>
<p><span class="math display">\[(\bar{X}-\bar{Y}) \pm t_{\alpha/2,\; n_X+n_Y-2} \cdot \hat\sigma_{\hat{\Delta}}\]</span></p>
<div class="PARAGRAPH">
<p>When assume equal variances?</p>
</div>
<p>Both of the books only present the case when the variances are equal. It does make the mathematics of the <span class="math inline">\(t\)</span> distribution better, in the sense that the distribution of <span class="math inline">\(T_{\Delta,pooled}\)</span> is exactly <span class="math inline">\(t\)</span> distributed with degrees of freedom that we can easily write down and work with. The distribution of our <span class="math inline">\(T\)</span> random variable is messy when we don’t assume equal variance, and we have to approximate it’s distribution with a <span class="math inline">\(t\)</span>. Moreover, in all realistic settings, you are measuring the same <em>type</em> of feature on both groups, so they should be on the same scale, and so it is not completely implausible that the variances are equal.</p>
<p>However, it is also the case that the that the same thing that divides them into two groups (men vs women; treatment vs control; etc) also means that may have a more variable response in one group than another. So the short answer is that there’s rarely any good reason to assume the variances are equal, and we have standard strategies that we don’t have to make that assumptions. In practice, it is rare that practitioners assume equal variance.</p>
<p>On the other hand, if we had more than one group we were comparing, the standard analysis (ANOVA) routinely assumes the same variance, just like we do in regression. And the pooled estimate of variance is what is used in this case. So it is useful to be familiar with the concept of pooled variance, in particular.</p>
<div class="QUESTION">
<div class="block-title">
<p><strong>Exercise/Question</strong></p>
</div>
<p>Show that the estimate of variance in regression when <span class="math inline">\(X\)</span> is categorical reduces to <span class="math inline">\(S^2_{pooled}\)</span> given above.</p>
</div>
</section>
<section id="example-redo" class="level3">
<h3 class="anchored" data-anchor-id="example-redo">Example Redo</h3>
<p>Let’s go back to our example, and consider what we would have if we assumed the same variance.</p>
<p>We need to calculated the pooled estimate of standard deviation, <span class="math display">\[S_{pooled}^2 = \frac{(n-1)S_x^2 + (m-1)S_y^2}{m+n-2} = \frac{(14)(12^2) + (19)(11.84)^2}{15+20-2} \approx 141.80 \;\Rightarrow\; S_p \approx 11.91\]</span> This is compared to the individual estimate in each group, <span class="math inline">\(S_X=12\)</span> and <span class="math inline">\(S_y=11.84\)</span>. As expected, it is between these two estimates.</p>
<p>This gives us the estimate of standard error of <span class="math inline">\(\hat\Delta\)</span> as <span class="math display">\[S_{\hat\Delta,pooled}=S_{pooled}\sqrt{\tfrac{1}{n_X}+\tfrac{1}{n_Y}}=11.91*\sqrt{1/20+1/15}=11.91*0.34=4.07\]</span> When we allowed for different variances we got <span class="math inline">\(S_{\hat\Delta}=4.06\)</span>, so quite similar. This isn’t surprising, since the estimates of standard deviation in each group are quite close.</p>
<p>Our degrees of freedom is <span class="math inline">\(n_X+n_Y-2=33\)</span>, again, close to <span class="math inline">\(\nu\)</span> above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.05</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">33</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.034515</code></pre>
</div>
</div>
<p>our confidence interval as <span class="math display">\[\hat{\Delta}\pm t_{\nu,\alpha} S_{\hat{\Delta},pooled}=11.2\pm 2.03 \cdot 4.07=11.2\pm 8.28\]</span> So we basically get all of the same answers as assuming different variances, which is <em>expected</em> when you start with two groups with similar standard deviations. However, with larger differences in <span class="math inline">\(S_X\)</span> and <span class="math inline">\(S_Y\)</span> and greater differences in sample size, you can get larger differences.</p>
</section>
</section>
<section id="paired-data" class="level2">
<h2 class="anchored" data-anchor-id="paired-data">Paired Data</h2>
<p>We have considered the case of two independent groups. But what about our examples of when our data is paired? Now we have dependency between our <span class="math inline">\(X\)</span> data and our <span class="math inline">\(Y\)</span> data.</p>
<p>The natural way of thinking about our data is to look at <em>differences</em> <span class="math display">\[D_i=X_i-Y_i\]</span> Then <span class="math display">\[
\begin{aligned}
E(D_i)&amp;=\mu_X-\mu_Y\\
\sigma^2_D=var(D_i)&amp;=var(X_i)+var(Y_i)-2 cov(X_i,Y_i)\\
&amp;= \sigma_X^2+\sigma_Y^2-2 \rho \sigma_X\sigma_Y
\end{aligned}
\]</span> where <span class="math inline">\(\rho\)</span> is the correlation of <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span>, if we assume the correlation is the same for all pairs <span class="math inline">\(i\)</span>.</p>
<section id="estimation-1" class="level3">
<h3 class="anchored" data-anchor-id="estimation-1">Estimation</h3>
<p>We still want to estimate <span class="math inline">\(\Delta=\mu_X-\mu_Y\)</span>. How does our estimate of <span class="math inline">\(\Delta\)</span> change if we have paired data?</p>
<p>First we note that <span class="math display">\[\bar{X}-\bar{Y}=\frac{1}{n}\sum_{i=1}^n(X_i-Y_i)=\bar{D}\]</span> So in fact our previous estimator <span class="math inline">\(\hat{\Delta}=\bar{X}-\bar{Y}=\bar{D}\)</span> will <em>also</em> be the average of their pair-wise differences.</p>
<p>Similarly, <span class="math display">\[E(\hat{\Delta})=E(\bar{D})=E(\bar{X})-E(\bar{Y})=\mu_X-\mu_Y\]</span> So we are clearly still using the same estimator and it is still an unbiased estimator of <span class="math inline">\(\Delta\)</span>.</p>
<p>However, the variance changes. For paired data <span class="math display">\[\sigma^2_{\bar{D}}=var(\bar{D})=var(\bar{X}-\bar{Y})=\frac{1}{n}(\sigma^2_X+\sigma^2_Y-2\rho \sigma_X\sigma_Y)\]</span> If we had instead collected the data on independent groups of units (assuming the same size <span class="math inline">\(n\)</span> in each group) we have, <span class="math display">\[var(\hat\Delta)=var(\bar{X}-\bar{Y})=\frac{1}{n}(\sigma_X^2+\sigma^2_Y)\]</span></p>
<p>So you can see that if there is a strong correlation between the <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> the variance of your estimator will be quite different. In fact, if there is a strong <em>positive</em> correlation, then the variance of <span class="math inline">\(\hat\Delta\)</span> will be much smaller, and thus you will have a more accurate estimate of <span class="math inline">\(\mu_X-\mu_Y\)</span>.</p>
<p>We frequently expect positive correlation – the pairing is usually of units that are similar to each other (or the same) so when <span class="math inline">\(X_i\)</span> is larger on average than the population <span class="math inline">\(X\)</span>, the same is true of <span class="math inline">\(Y_i\)</span>. For this reason, if you can construct a paired study, rather than independent observations in each group, this is usually a better <em>design</em> for how to collect your data. This makes sense if you think about how we can write our paired analysis as an analysis of the differences; we remove all of the things that stay the same for the pair and only measure what has changed. This removes variability from other sources. Think of our example of members of the same household – they have the same environment, the same standard of living, the same familial history. So looking at the difference of a younger and older member of the household can focus in on the generational effect.</p>
</section>
<section id="ci" class="level3">
<h3 class="anchored" data-anchor-id="ci">CI</h3>
<p>Again, we will need to estimate <span class="math inline">\(\sigma^2_{\bar{D}}\)</span>. Since we are just talking about the standard error of the mean of <span class="math inline">\(D_i\)</span>, we will use our standard estimate of the standard deviation of the <em>differences</em>, <span class="math inline">\(\sigma_{D}^2\)</span>, <span class="math display">\[S_{D}^2=\frac{1}{n-1}\sum_{i=1}^n(D_i-\bar{D})^2=\frac{1}{n-1}\sum_{i=1}^n((X_i-Y_i)-(\bar{X}-\bar{Y}))^2\]</span> We then define <span class="math display">\[T_{D}=\frac{\bar{D}-\mu_D}{S_{\bar{D}}}=\frac{(\bar{X}-\bar{Y})-(\mu_X-\mu_Y)}{S_D/\sqrt{n}}\]</span> If we assume the <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> are each normally distributed, then so is <span class="math inline">\(D_i\)</span>, so we have <span class="math display">\[T_{D}\sim t_{n-1},\]</span> and a CI given by <span class="math display">\[\bar{D}\pm t_{n-1,\alpha/2}S_{\bar{D}}.\]</span> Alternatively, for large sample sizes <span class="math inline">\(n\)</span>, we can use the CLT and have <span class="math display">\[\bar{D}\pm z_{\alpha/2}S_{\bar{D}}.\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice how everything is exactly the same as dealing with the mean of a single population, <span class="math inline">\(\bar{X}\)</span>, only we have now just replaced <span class="math inline">\(X_i\)</span> with <span class="math inline">\(D_i=X_i-Y_i\)</span>.</p>
</div>
</div>



</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-agresti2021" class="csl-entry" role="listitem">
Agresti, Alan, and Maria Kateri. 2021. <em>Foundations of Statistics for Data Scientists</em>. Chapman; Hall/CRC.
</div>
<div id="ref-rice2006" class="csl-entry" role="listitem">
Rice, John A. 2006. <em>Mathematical Statistics and Data Analysis</em>. 3rd ed. Duxbury Press.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Indeed, since the MLE of a function of parameter is just that function of the MLE, <span class="math inline">\(\hat\Delta\)</span> is indeed the MLE of <span class="math inline">\(\Delta\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><span class="math inline">\(\nu = \frac{\left(\frac{s_X^2}{n_X} + \frac{s_Y^2}{n_Y}\right)^2}{\frac{(s_X^2 / n_X)^2}{n_X - 1} + \frac{(s_Y^2 / n_Y)^2}{n_Y - 1}}\)</span> and is bounded between <span class="math inline">\(\min(n_X-1, n_Y-1)\)</span> and <span class="math inline">\((n_X + n_Y - 2)\)</span>. <a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/stat135\.berkeley\.edu\/spring-2026");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>